services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: syferr
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: blog_db
    ports:
      - 5432:5432
    networks:
      - blog_network
    
networks:
  blog_network:
    driver: bridge
  
  # adminer:
  #   image: adminer
  #   restart: always
    